// scripts/pr-pack.js — `buildPRBody(cwd)` assembles a PR description
// from pipeline artifacts. Tests the pure builder against fixture trees.

const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const { makeTargetProject, seedGate, cleanup } = require("./_helpers");
const { buildPRBody } = require("../scripts/pr-pack");

let _dirs = [];
function track(cwd) { _dirs.push(cwd); return cwd; }
test.afterEach?.(() => { _dirs.forEach(cleanup); _dirs = []; });

function writePipelineFile(cwd, rel, body) {
  const full = path.join(cwd, "pipeline", rel);
  fs.mkdirSync(path.dirname(full), { recursive: true });
  fs.writeFileSync(full, body);
}

test("buildPRBody on empty pipeline produces a placeholder body", () => {
  const cwd = track(makeTargetProject());
  const body = buildPRBody(cwd);
  assert.match(body, /Pipeline-produced PR/);
  assert.match(body, /no pipeline\/brief\.md found/);
  assert.match(body, /Produced by stagecraft/);
});

test("buildPRBody pulls the title from the brief's H1", () => {
  const cwd = track(makeTargetProject());
  writePipelineFile(cwd, "brief.md", "# Add SMS opt-in to user settings\n\n## 1. Problem\n\nFoo\n");
  const body = buildPRBody(cwd);
  assert.match(body, /^# Add SMS opt-in to user settings/m);
});

test("buildPRBody extracts §Problem from brief into Summary", () => {
  const cwd = track(makeTargetProject());
  writePipelineFile(cwd, "brief.md",
    "# Title\n\n## 1. Problem\n\nUsers can't opt out of marketing emails today.\n\n## 2. Stories\n\n…\n");
  const body = buildPRBody(cwd);
  assert.match(body, /## Summary/);
  assert.match(body, /Users can't opt out of marketing emails today/);
});

test("buildPRBody includes per-role PR summary files (pr-*.md)", () => {
  const cwd = track(makeTargetProject());
  writePipelineFile(cwd, "pr-backend.md", "API surface changes: PATCH /preferences added.");
  writePipelineFile(cwd, "pr-frontend.md", "New /settings/notifications page.");
  const body = buildPRBody(cwd);
  assert.match(body, /## Per-role PR summaries/);
  assert.match(body, /### backend/);
  assert.match(body, /### frontend/);
  assert.match(body, /PATCH \/preferences added/);
  assert.match(body, /New \/settings\/notifications page/);
});

test("buildPRBody renders the merged build gate's workstreams table", () => {
  const cwd = track(makeTargetProject());
  seedGate(cwd, "stage-04", {
    stage: "stage-04",
    status: "PASS",
    workstreams: [
      { workstream: "backend", host: "codex", status: "PASS" },
      { workstream: "frontend", host: "claude-code", status: "WARN" },
    ],
  });
  const body = buildPRBody(cwd);
  assert.match(body, /## Build status/);
  assert.match(body, /\| backend \| codex \| PASS \|/);
  assert.match(body, /\| frontend \| claude-code \| WARN \|/);
});

test("buildPRBody includes test results when stage-06 gate exists", () => {
  const cwd = track(makeTargetProject());
  seedGate(cwd, "stage-06", {
    stage: "stage-06",
    status: "PASS",
    tests_total: 42,
    tests_passed: 42,
    tests_failed: 0,
    all_acceptance_criteria_met: true,
    criterion_to_test_mapping_is_one_to_one: true,
  });
  const body = buildPRBody(cwd);
  assert.match(body, /## Test results/);
  assert.match(body, /- Total: 42/);
  assert.match(body, /- Passed: 42/);
  assert.match(body, /All acceptance criteria met/);
  assert.match(body, /1:1 criterion-to-test mapping/);
});

test("buildPRBody mentions the design spec when one exists", () => {
  const cwd = track(makeTargetProject());
  writePipelineFile(cwd, "design-spec.md", "# Design\n\nThe design.");
  const body = buildPRBody(cwd);
  assert.match(body, /## Design/);
  assert.match(body, /pipeline\/design-spec\.md/);
});

test("buildPRBody is deterministic except for the generated-at timestamp", () => {
  const cwd = track(makeTargetProject());
  writePipelineFile(cwd, "brief.md", "# Static brief\n\n## 1. Problem\n\nStatic.\n");
  const b1 = buildPRBody(cwd);
  const b2 = buildPRBody(cwd);
  // Strip the timestamp comment line and compare the rest.
  const norm = (s) => s.replace(/<!-- Generated by `scripts\/pr-pack\.js` on .* -->/, "<TS>");
  assert.equal(norm(b1), norm(b2));
});
