#!/usr/bin/env node
// pr-pack.js — assemble the per-role pipeline/pr-*.md files plus the
// merged build gate into a single PR description ready for GitHub.
//
// Usage:
//   node scripts/pr-pack.js                  # write to stdout
//   node scripts/pr-pack.js --out PR_BODY.md # write to a file
//   node scripts/pr-pack.js --cwd /target    # read pipeline/ from elsewhere

const fs = require("node:fs");
const path = require("node:path");

function parseArgs(argv) {
  const a = { cwd: process.cwd(), out: null };
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === "--out") a.out = argv[++i];
    else if (argv[i] === "--cwd") a.cwd = argv[++i];
  }
  return a;
}

function readFileSafe(p) {
  try { return fs.readFileSync(p, "utf8"); } catch { return null; }
}

function readJSONSafe(p) {
  const t = readFileSafe(p);
  if (!t) return null;
  try { return JSON.parse(t); } catch { return null; }
}

function buildPRBody(cwd) {
  const out = [];
  const pipelineDir = path.join(cwd, "pipeline");
  const brief = readFileSafe(path.join(pipelineDir, "brief.md"));
  const designSpec = readFileSafe(path.join(pipelineDir, "design-spec.md"));
  const stage04 = readJSONSafe(path.join(pipelineDir, "gates", "stage-04.json"));
  const stage06 = readJSONSafe(path.join(pipelineDir, "gates", "stage-06.json"));

  // Title: pull the first H1 from brief if present, else generic
  const title = (brief && brief.match(/^#\s+(.+)$/m)) ? brief.match(/^#\s+(.+)$/m)[1] : "Pipeline-produced PR";

  out.push(`# ${title}`);
  out.push("");
  out.push(`<!-- Generated by \`scripts/pr-pack.js\` on ${new Date().toISOString()} -->`);
  out.push("");

  // Summary section
  out.push("## Summary");
  if (brief) {
    const problem = brief.match(/##\s+1\.\s+Problem\s*\n+([\s\S]*?)(?=\n## |$)/);
    if (problem) {
      out.push(problem[1].trim());
    } else {
      out.push("(brief.md has no §Problem section; see pipeline/brief.md)");
    }
  } else {
    out.push("(no pipeline/brief.md found)");
  }
  out.push("");

  // Acceptance criteria
  if (brief) {
    const ac = brief.match(/##\s+3\.\s+Acceptance criteria\s*\n+([\s\S]*?)(?=\n## |$)/);
    if (ac) {
      out.push("## Acceptance criteria");
      out.push(ac[1].trim());
      out.push("");
    }
  }

  // Per-role PR summaries
  const prSummaries = fs.existsSync(pipelineDir)
    ? fs.readdirSync(pipelineDir).filter((f) => f.startsWith("pr-") && f.endsWith(".md"))
    : [];
  if (prSummaries.length > 0) {
    out.push("## Per-role PR summaries");
    out.push("");
    for (const f of prSummaries.sort()) {
      const role = f.replace(/^pr-/, "").replace(/\.md$/, "");
      const body = readFileSafe(path.join(pipelineDir, f));
      out.push(`### ${role}`);
      out.push("");
      out.push(body || `(empty: ${f})`);
      out.push("");
    }
  }

  // Build gate workstream summary
  if (stage04 && Array.isArray(stage04.workstreams)) {
    out.push("## Build status");
    out.push("");
    out.push("| Workstream | Host | Status |");
    out.push("|---|---|---|");
    for (const w of stage04.workstreams) {
      out.push(`| ${w.workstream} | ${w.host || "—"} | ${w.status} |`);
    }
    out.push("");
  }

  // Test results
  if (stage06) {
    out.push("## Test results");
    out.push("");
    out.push(`- Status: ${stage06.status}`);
    if (typeof stage06.tests_total === "number") out.push(`- Total: ${stage06.tests_total}`);
    if (typeof stage06.tests_passed === "number") out.push(`- Passed: ${stage06.tests_passed}`);
    if (typeof stage06.tests_failed === "number") out.push(`- Failed: ${stage06.tests_failed}`);
    if (stage06.all_acceptance_criteria_met === true) out.push(`- ✅ All acceptance criteria met`);
    if (stage06.criterion_to_test_mapping_is_one_to_one === true) out.push(`- ✅ 1:1 criterion-to-test mapping`);
    out.push("");
  }

  // Design spec reference
  if (designSpec) {
    out.push("## Design");
    out.push("");
    out.push(`Full design at \`pipeline/design-spec.md\`. ADRs at \`pipeline/adr/\`.`);
    out.push("");
  }

  // Trailer
  out.push("---");
  out.push("");
  out.push(`Produced by stagecraft. Pipeline artifacts in \`pipeline/\`; gates in \`pipeline/gates/\`.`);

  return out.join("\n") + "\n";
}

function main() {
  const args = parseArgs(process.argv.slice(2));
  const body = buildPRBody(args.cwd);
  if (args.out) {
    fs.writeFileSync(args.out, body);
    process.stderr.write(`Wrote PR body to ${args.out}\n`);
  } else {
    process.stdout.write(body);
  }
}

if (require.main === module) main();

module.exports = { buildPRBody };
